baseURL: "https://timschuetz.org" 
title: Tim Schütz
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1 
        - name: Writing
          url: papers/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4 
        - name: Teaching
          url: courses/
          weight: 5
        - name: CV
          url: cv.pdf
          weight: 6

params:
    description: "I'm a social scientist interested in data politics, digital cultures, and knowledge infrastructures. My most recent work has focused on the role of data for the governance of complex environmental problems and industrial disasters. I'm currently an independent researcher with the EcoGovLab at the University of California, Irvine. In summer 2026, I will begin a Marie Skłodowska-Curie postdoctoral fellowship at the IT University Copenhagen."
    author: Tim Schütz
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tim Schütz
          subtitle: "I'm a social scientist interested in data politics, digital cultures, and knowledge infrastructures. My most recent work has focused on the role of data for the governance of complex environmental problems and industrial disasters. I'm currently an independent researcher with the EcoGovLab at the University of California, Irvine. In summer 2026, I will begin a Marie Skłodowska-Curie postdoctoral fellowship at the IT University Copenhagen."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Projects
              url: projects/
            - name: Writing
              url: papers/
            - name: Talks
              url: talks/
            - name: Teaching
              url: courses/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:tschuetz@uci.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=KQlghMUAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/timschuetz
        - name: Bluesky
          url: https://bsky.app/profile/timschutz.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tim Schütz"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
